config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root "rooms#index", as: "authenticated_root"
  end

  root "welcome#index"

  resources :rooms do
    resources :chats
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :room
  belongs_to :user

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :chats, dependent: :destroy
  has_many :tasks
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :room

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms
  has_many :chats, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "25x25>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :avatar]
    devise_parameter_sanitizer.for(:account_update) << [:username, :avatar]
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_room
  before_action :set_chat, except: [:create]

  def new
    c_params = chat_params
    c_params[:user_id] = current_user.id
    @chat = @room.chats.create
  end


  def create
    c_params = chat_params
    c_params[:user_id] = current_user.id
    @chat = @room.chats.create(c_params)

    if @chat.save
      redirect_to @room
    else
      render "new"
    end
  end

  def update
    if @chat.update(chat_params)
      redirect_to @room
    else
      render "edit"
    end
  end

  def destroy
    @chat.destroy
    redirect_to room_path(@room)
  end

  private
    def chat_params
      params[:chat].permit(:comment, :user_id)
    end

    def set_room
      @room = Room.find(params[:room_id])
    end

    def set_chat
      @chat = @room.chats.find(params[:id])
    end

    def room_params
      @room = Room.find(params[:room_id])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all.order("created_at DESC")
  end

  def show
    @chats = @room.chats.all.order("created_at DESC")
    @tasks = @room.tasks.all.order("created_at DESC")
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to @room
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to @room
    else
      render "edit"
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

    def room_params
      params.require(:room).permit(:title, :description, :image)
    end

    def find_room
      @room = Room.find(params[:id])
    end

    def find_chat
      @chat = Chat.find(params[:room_id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_room
  before_action :set_task, except: [:create]

  def new
    @task = @room.tasks.create
  end

  def create
    @task = @room.tasks.create(task_params)
    if @task.save
      redirect_to @room
    else
      render "new"
    end
  end

  def destroy
    if @task.destroy
      flash[:success] = "タスクを削除しました。"
    else
      flash[:error] = "削除できませんでした。"
    end
    redirect_to @room
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to @room, notice: "Todo item completed"
  end

  private
    def task_params
      params[:task].permit(:content)
    end

    def set_room
      @room = Room.find(params[:room_id])
    end

    def set_task
      @task = @room.tasks.find(params[:id])
    end


    def room_params
      @room = Room.find(params[:room_id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/_form.html.erb
<%= simple_form_for [@room, @room.chats.build] do |f| %>
  <%= f.input :comment, class: "form-control" %>
  <p class="text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/chats/edit.html.erb
<%= simple_form_for [@room, @chat] do |f| %>
  <%= f.input :comment, class: "form-control" %>
  <p class="text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-center" id="footer">
  <small>©straysheep</small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Botch² Online", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Room", new_room_path, class: "btn btn-primary" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_user.avatar.url(:thumb) %>
              <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path, class: "btn btn-info" %></li>
          <li><%= link_to "会員登録", new_user_registration_path, class: "btn btn-success" %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MokuOnline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  <% else %>
    <%= render "welcome/header" %>
    <%= yield %>
  <% end %>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |f| %>
  <%= image_tag @room.image.url(:medium) %>
  <%= f.input :image, as: :file %>
  <%= f.input :title, class: "form-control" %>
  <%= f.input :description, class: "form-control" %>
  <br>
  <p class="text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/rooms/edit.html.erb
<div class="col-md-7 col-md-offset-3">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title">Room編集</h2>
    </div>
    <div class="panel-body">
      <%= render "form" %>
      <hr>
      <p class="text-right">
        <%= link_to "Cancel", room_path(@room), class: "btn btn-default" %>
      </p>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div id="rooms" class="transitions-enabled">
  <% @rooms.each do |room| %>
    <div class="panel panel-primary box">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= room.title %>
        </h3>
      </div>
      <div class="panel-body">
        <p class="text-center">
          <%= link_to room do %>
            <%= image_tag room.image.url(:medium) %>
          <% end %>
        </p>
        <hr>
        <%= room.description %>
      </div>
      <div class="panel-footer text-right">
        <%= link_to "Enter", room, class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="col-md-7 col-md-offset-3">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title">新規Room作成</h2>
    </div>
    <div class="panel-body">
      <%= render "form" %>
      <hr>
      <p class="text-right">
        <%= link_to "Cancel", root_path, class: "btn btn-default" %>
      </p>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="col-md-6">
  <div class="row">
    <div class="col-md-12">

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            <i class="fa fa-flask" aria-hidden="true"></i>&ensp;<%= @room.title %>
          </h3>
        </div>
        <div class="panel-body">
          <p class="text-center">
            <%= image_tag @room.image.url(:medium) %>
          </p>
        </div>
        <div class="panel-footer">
          <%= @room.description %>
        </div>
      </div>

    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">
            <i class="fa fa-comments" aria-hidden="true"></i>&ensp;チャット一覧
          </h3>
        </div>
        <div class="panel-body">
          <% @chats.each do |chat| %>
          <div class="panel panel-default chat-area">
            <div class="panel-heading">
              <div class="media">
                <div class="pull-left">
                  <%= image_tag chat.user.avatar.url(:thumb) %>
                  <%= chat.user.username %>
                </div>
                <div class="media-body">
                  <p>
                    <%= chat.comment %>
                  </p>
                </div>
              </div>
              <% if chat.user == current_user %>
                <hr>
                <div class="text-right">
                  <div class="btn-group btn-group-sm">
                    <%= link_to edit_room_chat_path(@room, chat), class: "btn btn-warning" do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to room_chat_path(@room, chat), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" do %>
                      <i class="fa fa-trash-o" aria-hidden="true"></i>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="row">

    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-tasks" aria-hidden="true"></i>&ensp; Task List</h3>
        </div>
        <div class="panel-body">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>Check</th>
                <th>Tasks</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              <%= render @room.tasks %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-cog" aria-hidden="true"></i>&ensp;Room設定</h3>
        </div>
        <div class="panel-body">

          <p class="text-right">
            <%= @room.created_at %>
            <br>
          </p>
        </div>
          <div class="btn-group-justified">
            <%= link_to  root_path, class: "btn btn-default" do %>
              <i class="fa fa-home" aria-hidden="true"></i>
            <% end %>
            <%= link_to  edit_room_path(@room), class: "btn btn-warning" do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
            <%= link_to room_path(@room), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          </div>
      </div>
    </div>

  </div>
  <div class="row" data-spy="affix" data-offset-top="150" data-offset-bottom="200">
    <div class="col-md-12">
      <ul class="nav nav-pills nav-justified">
        <li class="active"><a href="#chat" data-toggle="tab"><i class="fa fa-commenting" aria-hidden="true"></i>&ensp;チャット</a></li>
        <li><a href="#task" data-toggle="tab"><i class="fa fa-tasks" aria-hidden="true"></i>&ensp;Task</a></li>
      </ul>
      <div class="tab-content">
        <div class="panel tab-pane active" id="chat">
          <div class="panel-body">
            <%= render "chats/form" %>
          </div>
          <div class="panel-footer">
            チャット用フォーム
          </div>
        </div>
        <div class="panel tab-pane" id="task">
          <div class="panel-body">
            <%= render "tasks/form" %>
          </div>
          <div class="panel-footer">
            タスク用フォーム
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for [@room, @room.tasks.build] do |f| %>
  <%= f.input :content, class: "form-control" %>
  <p class="text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
      <% if task.completed? %>
        <tr>
          <td>
            <%= link_to complete_room_task_path(@room, task.id), method: :patch do %>
              <i class="fa fa-check-square" aria-hidden="true"></i>
            <% end %>
          </td>
          <td>
            <strike><%= task.content %></strike>
          </td>
          <td>
            <%= link_to room_task_path(@room, task.id), method: :delete, data: { confirm: "本当に削除しますか？" } do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% else %>
        <tr>
          <td>
            <%= link_to complete_room_task_path(@room, task.id), method: :patch do %>
              <i class="fa fa-square-o" aria-hidden="true"></i>
            <% end %>
          </td>
          <td>
            <%= task.content %>
          </td>
          <td>
            <%= link_to room_task_path(@room, task.id), method: :delete, data: { confirm: "本当に削除しますか？" } do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-default welcome-nav">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Botch² Online(ver.0.9.9)", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Room", new_room_path, class: "btn btn-primary" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_user.avatar.url(:thumb) %>
              <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to new_user_session_path, class: "btn btn-info" do %>
            <i class="fa fa-futbol-o" aria-hidden="true"></i> ログイン
            <% end %>
          </li>
          <li><%= link_to new_user_registration_path, class: "btn btn-success" do %>
            <i class="fa fa-user-plus" aria-hidden="true"></i> 新規登録
            <% end %>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="container-fluid welcome-mv">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center main-title">
      <h1>Botch² Online</h1>
      <p>
        Botch(ぼっち)オンラインは、ずーっと１人で学習していてもしんどいし、効率が悪い。
        学習仲間を見つけて、学習が三日坊主で終わらないよう学習仲間を見つけるお手伝いをします。
      </p>
    </div>
    <div class="col-md-4 col-md-offset-6 main-info">
      <div class="panel panel-primary mv-panel text-center">
        <div class="panel-heading">
          <h3 class="panel-title">ユーザー登録</h3>
        </div>
        <div class="panel-body">
          現在はβ版となっています。適当なメールアドレスでも登録可能です。
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ergo, inquit, tibi Q. Haec et tu ita posuisti, et verba vestra sunt. Certe non potest. Videsne quam sit magna dissensio? Duo Reges: constructio interrete.
        </div>
        <div class="panel-footer">
          <%= link_to new_user_registration_path, class: "btn btn-group-justified btn-success" do %>
            <i class="fa fa-user-plus" aria-hidden="true"></i> 新規登録
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <h2><i class="fa fa-graduation-cap" aria-hidden="true"></i> ログインしてボードを作成します</h2>
    <hr>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">ここにログイン時のindex</h3>
        </div>
        <div class="panel-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Utilitatis causa amicitia est quaesita. Summum a vobis bonum voluptas dicitur. Isto modo ne improbos quidem, si essent boni viri. Fatebuntur Stoici haec omnia dicta esse praeclare, neque eam causam Zenoni desciscendi fuisse. Erit enim instructus ad mortem contemnendam, ad exilium, ad ipsum etiam dolorem. Non est igitur summum malum dolor.
        </div>
        <div class="panel-footer">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quae diligentissime contra Aristonem dicuntur a Chryippo. Ad eas enim res ab Epicuro praecepta dantur. Et ille ridens: Video, inquit, quid agas; Iam in altera philosophiae parte. Aliter enim explicari, quod quaeritur, non potest. Duo Reges: constructio interrete. Quae cum essent dicta, finem fecimus et ambulandi et disputandi. Teneo, inquit, finem illi videri nihil dolere.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">タイトル</h3>
        </div>
        <div class="panel-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tum Torquatus: Prorsus, inquit, assentior; Frater et T. Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.
        </div>
        <div class="panel-footer">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Illum mallem levares, quo optimum atque humanissimum virum, Cn. Quorum altera prosunt, nocent altera. Duo Reges: constructio interrete. Dic in quovis conventu te omnia facere, ne doleas. Numquam facies. Quamquam haec quidem praeposita recte et reiecta dicere licebit. Primum quid tu dicis breve? Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. Atqui reperies, inquit, in hoc quidem pertinacem; Conferam avum tuum Drusum cum C.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">タイトル</h3>
        </div>
        <div class="panel-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aeque enim contingit omnibus fidibus, ut incontentae sint. Cur id non ita fit? Duo Reges: constructio interrete. Recte dicis; An est aliquid, quod te sua sponte delectet? Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Longum est enim ad omnia respondere, quae a te dicta sunt. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse;
        </div>
        <div class="panel-footer">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. O magnam vim ingenii causamque iustam, cur nova existeret disciplina! Perge porro. Tum Piso: Quoniam igitur aliquid omnes, quid Lucius noster? Duo Reges: constructio interrete. Quia dolori non voluptas contraria est, sed doloris privatio. Hoc enim constituto in philosophia constituta sunt omnia. Huic mori optimum esse propter desperationem sapientiae, illi propter spem vivere.
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="container room">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag("room.png", class: "img-responsive") %>
    </div>
    <div class="col-md-4">
      <h3><i class="fa fa-flask" aria-hidden="true"></i> Roomの機能</h3>
      <hr>
      <div class="panel panel-default">
        <div class="panel-body">
          <ul>
            <li>Room作成</li>
            <li>参加機能</li>
            <li>メンバー管理</li>
            <li>チャット機能</li>
            <li>タスク機能</li>
          </ul>
        </div>
        <div class="panel-footer">

        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="container chat">
  <div class="row">
    <div class="col-md-4">
      <h3><i class="fa fa-comments-o" aria-hidden="true"></i> チャット、タスク機能</h3>
      <hr>
      <div class="panel panel-default">
        <div class="panel-body">
          <ul>
            <li>チャット機能
              <ul>
                <li>チャット機能は、追従</li>
              </ul>
            </li>
            <li>チャット、タスクはタブで切り替え</li>
            <li>こんなもんや</li>
          </ul>
        </div>
        <div class="panel-footer">

        </div>
      </div>
    </div>
    <div class="col-md-8">
      <%= image_tag "chat.png", class: "img-responsive" %>
    </div>
  </div>
</div>